apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace.name }}
  name: {{ .Values.service.name }}
spec:
  selector:
    app: techtrends
  type: {{ .Values.service.type }}    
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
