namespace:
  name: sandbox
replicaCount: 1

image:
  repository: techtrends
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: techtrends
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

resources:
  requests:
    memory: 64Mi
    cpu: 250m
  limits:
    memory: 128Mi
    cpu: 500m

probes:
  liveness:
    path: /healthz
    port: 3111
  readiness:
    path: /healthz
    port: 3111

containerPort: 3111
