namespace: 
  name: sandbox
replicaCount: 1
image:
  repository: techtrends
  tag: latest
  pullPolicy: IfNotPresent
resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"
service:
  name: techtrends
  type: ClusterIP
  port: 4111
  targetPort: 3111
  protocol: TCP
containerPort: 3111
probes:
  liveness:
    path: /healthz
    port: 3111
  readiness:
    path: /healthz
    port: 3111
